package com.mycompany.maventestproject;
// Generated 22.02.2016 20:24:28 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="test"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int age;
     private boolean isAdmin;
     private Date createdDate;

    public User() {
    }

    public User(String name, int age, boolean isAdmin, Date createdDate) {
       this.name = name;
       this.age = age;
       this.isAdmin = isAdmin;
       this.createdDate = createdDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true /*, nullable=false*/)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", /*nullable=false,*/ length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="age" /*, nullable=false*/)
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    
    @Column(name="is_admin" /*, nullable=false*/)
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", /*nullable=false,*/ length=0)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


